root: true
env:
  node: true
  es2022: true
  jest/globals: true
plugins:
  - jest
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:jest/recommended
  - plugin:jest/style
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
