env:
  node: true
  es2022: true
  jest/globals: true
plugins:
  - jest
extends:
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:jest/style
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  arrow-spacing: error
  brace-style:
  - 2
  - 1tbs
  camelcase:
  - 2
  - properties: always
  comma-dangle:
  - 2
  - always-multiline
  comma-spacing:
  - 2
  - after: true
    before: false
  curly:
  - 2
  - all
  dot-location:
  - 2
  - property
  eol-last:
  - 2
  - always
  eqeqeq:
  - 2
  - always
  func-call-spacing:
  - 2
  - never
  indent:
  - 2
  - 4
  key-spacing:
  - 2
  - afterColon: true
    beforeColon: false
  keyword-spacing:
  - 2
  - after: true
    before: true
  new-parens:
  - 2
  - always
  no-duplicate-imports:
  - 2
  - includeExports: true
  no-empty:
  - 2
  - allowEmptyCatch: true
  no-extend-native: error
  no-unused-vars:
  - 2
  - args: after-used
    argsIgnorePattern: ^_
  object-curly-spacing:
  - 2
  - always
  operator-linebreak:
  - 2
  - before
  quotes:
  - 2
  - single
  - allowTemplateLiterals: true
  semi:
  - 2
  - always
  space-before-function-paren:
  - 2
  - anonymous: never
    asyncArrow: always
    named: never
  template-curly-spacing:
  - 2
  - never
